"""
Complete brand list extracted from turbo.az HTML dropdown
"""

TURBO_AZ_BRANDS = [
    {"id": "280", "name": "Abarth"},
    {"id": "28", "name": "Acura"},
    {"id": "30", "name": "Alfa Romeo"},
    {"id": "859", "name": "Anyang Kinland"},
    {"id": "771", "name": "AODES"},
    {"id": "86", "name": "Aston Martin"},
    {"id": "268", "name": "ATV"},
    {"id": "9", "name": "Audi"},
    {"id": "419", "name": "Avatr"},
    {"id": "274", "name": "Avia"},
    {"id": "218", "name": "Baic"},
    {"id": "327", "name": "Bajaj"},
    {"id": "226", "name": "BAW"},
    {"id": "642", "name": "BENDA"},
    {"id": "19", "name": "Bentley"},
    {"id": "387", "name": "Bestune"},
    {"id": "136", "name": "BMC"},
    {"id": "3", "name": "BMW"},
    {"id": "62", "name": "BMW Alpina"},
    {"id": "92", "name": "Brilliance"},
    {"id": "736", "name": "BRP"},
    {"id": "84", "name": "Buick"},
    {"id": "51", "name": "BYD"},
    {"id": "395", "name": "C.Moto"},
    {"id": "38", "name": "Cadillac"},
    {"id": "220", "name": "Can-Am"},
    {"id": "259", "name": "CFMOTO"},
    {"id": "163", "name": "Changan"},
    {"id": "52", "name": "Chery"},
    {"id": "41", "name": "Chevrolet"},
    {"id": "10", "name": "Chrysler"},
    {"id": "27", "name": "Citroen"},
    {"id": "76", "name": "Dacia"},
    {"id": "11", "name": "Daewoo"},
    {"id": "91", "name": "DAF"},
    {"id": "66", "name": "Daihatsu"},
    {"id": "148", "name": "Dayun"},
    {"id": "471", "name": "Denza"},
    {"id": "405", "name": "DFSK"},
    {"id": "162", "name": "Dnepr"},
    {"id": "60", "name": "Dodge"},
    {"id": "877", "name": "Dofern"},
    {"id": "117", "name": "DongFeng"},
    {"id": "147", "name": "Ducati"},
    {"id": "79", "name": "FAW"},
    {"id": "42", "name": "Ferrari"},
    {"id": "37", "name": "Fiat"},
    {"id": "2", "name": "Ford"},
    {"id": "478", "name": "Forthing"},
    {"id": "49", "name": "Foton"},
    {"id": "689", "name": "Freedom"},
    {"id": "870", "name": "FY"},
    {"id": "175", "name": "GAC"},
    {"id": "21", "name": "GAZ"},
    {"id": "72", "name": "Geely"},
    {"id": "376", "name": "Genesis"},
    {"id": "82", "name": "GMC"},
    {"id": "773", "name": "Golden Dragon"},
    {"id": "847", "name": "GST"},
    {"id": "50", "name": "GWM (Great Wall Motor)"},
    {"id": "383", "name": "Haima"},
    {"id": "142", "name": "Haojue"},
    {"id": "140", "name": "Harley-Davidson"},
    {"id": "242", "name": "Haval"},
    {"id": "12", "name": "Honda"},
    {"id": "388", "name": "Hongqi"},
    {"id": "110", "name": "HOWO"},
    {"id": "13", "name": "Hummer"},
    {"id": "461", "name": "Hycan"},
    {"id": "1", "name": "Hyundai"},
    {"id": "678", "name": "iCar"},
    {"id": "772", "name": "iHonzda"},
    {"id": "64", "name": "IJ"},
    {"id": "424", "name": "IM"},
    {"id": "411", "name": "Indian Motorcycle"},
    {"id": "15", "name": "Infiniti"},
    {"id": "116", "name": "Iran Khodro"},
    {"id": "74", "name": "Isuzu"},
    {"id": "253", "name": "ItalCar"},
    {"id": "67", "name": "Iveco"},
    {"id": "124", "name": "JAC"},
    {"id": "549", "name": "JAECOO"},
    {"id": "35", "name": "Jaguar"},
    {"id": "36", "name": "Jeep"},
    {"id": "384", "name": "JETOUR"},
    {"id": "462", "name": "Jiangmen"},
    {"id": "337", "name": "Jianshe"},
    {"id": "864", "name": "JIM"},
    {"id": "109", "name": "JMC"},
    {"id": "390", "name": "KAIYI"},
    {"id": "90", "name": "KamAz"},
    {"id": "406", "name": "Kanuni"},
    {"id": "420", "name": "Karry"},
    {"id": "139", "name": "Kawasaki"},
    {"id": "374", "name": "Kayo"},
    {"id": "338", "name": "Keeway"},
    {"id": "473", "name": "KG Mobility"},
    {"id": "282", "name": "Khazar"},
    {"id": "8", "name": "Kia"},
    {"id": "119", "name": "KrAZ"},
    {"id": "141", "name": "KTM"},
    {"id": "332", "name": "Kuba"},
    {"id": "872", "name": "KYC"},
    {"id": "5", "name": "LADA (VAZ)"},
    {"id": "43", "name": "Lamborghini"},
    {"id": "20", "name": "Land Rover"},
    {"id": "459", "name": "Leapmotor"},
    {"id": "14", "name": "Lexus"},
    {"id": "412", "name": "Li Auto"},
    {"id": "87", "name": "Lifan"},
    {"id": "46", "name": "Lincoln"},
    {"id": "238", "name": "Lotus"},
    {"id": "103", "name": "LuAz"},
    {"id": "414", "name": "Lynk & Co"},
    {"id": "677", "name": "M-Hero"},
    {"id": "329", "name": "Mack"},
    {"id": "867", "name": "Maextro"},
    {"id": "112", "name": "MAN"},
    {"id": "423", "name": "Maple"},
    {"id": "44", "name": "Maserati"},
    {"id": "100", "name": "MAZ"},
    {"id": "26", "name": "Mazda"},
    {"id": "326", "name": "McLaren"},
    {"id": "4", "name": "Mercedes"},
    {"id": "252", "name": "Mercedes-Maybach"},
    {"id": "47", "name": "Mercury"},
    {"id": "127", "name": "MG"},
    {"id": "769", "name": "Mikilon"},
    {"id": "31", "name": "Mini"},
    {"id": "146", "name": "Minsk"},
    {"id": "6", "name": "Mitsubishi"},
    {"id": "286", "name": "Mondial"},
    {"id": "81", "name": "Moskvich"},
    {"id": "243", "name": "Muravey"},
    {"id": "158", "name": "MV Agusta"},
    {"id": "324", "name": "Nama"},
    {"id": "409", "name": "Neta"},
    {"id": "415", "name": "Nio"},
    {"id": "7", "name": "Nissan"},
    {"id": "29", "name": "Opel"},
    {"id": "181", "name": "Otokar"},
    {"id": "114", "name": "PAZ"},
    {"id": "16", "name": "Peugeot"},
    {"id": "465", "name": "Polad"},
    {"id": "247", "name": "Polaris"},
    {"id": "396", "name": "Polestar"},
    {"id": "32", "name": "Porsche"},
    {"id": "681", "name": "QJMotor"},
    {"id": "467", "name": "Radar"},
    {"id": "105", "name": "RAF"},
    {"id": "272", "name": "Ravon"},
    {"id": "17", "name": "Renault"},
    {"id": "595", "name": "Renault Samsung"},
    {"id": "333", "name": "RKS"},
    {"id": "171", "name": "Roewe"},
    {"id": "18", "name": "Rolls-Royce"},
    {"id": "78", "name": "Rover"},
    {"id": "477", "name": "ROX (Polar Stone)"},
    {"id": "422", "name": "Royal Enfield"},
    {"id": "80", "name": "Saab"},
    {"id": "94", "name": "Saipa"},
    {"id": "377", "name": "SamAuto"},
    {"id": "108", "name": "Scania"},
    {"id": "59", "name": "SEAT"},
    {"id": "460", "name": "Seres Aito"},
    {"id": "133", "name": "Shacman"},
    {"id": "132", "name": "Shaolin"},
    {"id": "690", "name": "Sharmax"},
    {"id": "22", "name": "Skoda"},
    {"id": "399", "name": "Skywell"},
    {"id": "61", "name": "Smart"},
    {"id": "402", "name": "Soueast"},
    {"id": "45", "name": "Ssang Yong"},
    {"id": "34", "name": "Subaru"},
    {"id": "33", "name": "Suzuki"},
    {"id": "380", "name": "SYM"},
    {"id": "245", "name": "Tesla"},
    {"id": "39", "name": "Tofas"},
    {"id": "23", "name": "Toyota"},
    {"id": "233", "name": "Triumph"},
    {"id": "385", "name": "Tufan"},
    {"id": "464", "name": "TVS"},
    {"id": "53", "name": "UAZ"},
    {"id": "145", "name": "Ural"},
    {"id": "223", "name": "Vespa"},
    {"id": "410", "name": "VGV"},
    {"id": "868", "name": "Victoria"},
    {"id": "644", "name": "Victory"},
    {"id": "854", "name": "Vmoto"},
    {"id": "857", "name": "Voge"},
    {"id": "24", "name": "Volkswagen"},
    {"id": "386", "name": "Volta"},
    {"id": "25", "name": "Volvo"},
    {"id": "417", "name": "Voyah"},
    {"id": "404", "name": "Wuling"},
    {"id": "219", "name": "XCMG"},
    {"id": "680", "name": "Xiaomi"},
    {"id": "421", "name": "XPeng"},
    {"id": "381", "name": "Yadea"},
    {"id": "138", "name": "Yamaha"},
    {"id": "57", "name": "ZAZ"},
    {"id": "851", "name": "Zaza"},
    {"id": "403", "name": "ZEEKR"},
    {"id": "85", "name": "ZIL"},
    {"id": "285", "name": "Zonsen"},
    {"id": "143", "name": "Zontes"},
    {"id": "398", "name": "Zuk"},
    {"id": "217", "name": "ZX Auto"},
]
